#!/bin/bash
#PBS -N FSI_n20
#PBS -q cpu
#PBS -l select=1:ncpus=20:mpiprocs=20
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o /home/u10915539/fsi_project/build/20/job.log

apptainer exec /work/u10915539/amsc_mk_2025.sif bash -i -c "
    source /u/sw/etc/bash.bashrc &&
    module load gcc-glibc dealii &&
    cd /home/u10915539/fsi_project/build/20 &&
    mpirun -n 20 /home/u10915539/fsi_project/build/FSI_parallel
" > /home/u10915539/fsi_project/build/20/output.txt 2>&1
