#!/bin/bash
#PBS -N FSI_n14
#PBS -q cpu
#PBS -l select=1:ncpus=14:mpiprocs=14
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o /home/u10915539/fsi_project/build/14/job.log

apptainer exec /work/u10915539/amsc_mk_2025.sif bash -i -c "
    source /u/sw/etc/bash.bashrc &&
    module load gcc-glibc dealii &&
    cd /home/u10915539/fsi_project/build/14 &&
    mpirun -n 14 /home/u10915539/fsi_project/build/FSI_parallel
" > /home/u10915539/fsi_project/build/14/output.txt 2>&1
