#!/bin/bash
#PBS -N FSI_parallel
#PBS -q cpu
#PBS -l select=1:ncpus=20:mpiprocs=20
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -o /home/u10915539/fsi_project/fsi_output.log

apptainer exec /work/u10915539/amsc_mk_2025.sif bash -i -c "
    source /u/sw/etc/bash.bashrc &&
    module load gcc-glibc dealii &&
    mkdir -p /home/u10915539/fsi_project/build &&
    cd /home/u10915539/fsi_project/build &&
    cmake .. &&
    make -j8 &&
    mpirun -n 8 ./FSI_parallel
"
